### ISSUE TITLE
Remove logs

### ISSUE THREAD

**Issue by miguelslemos** [Team-SOFTsk/ObservableAdapter#2]
could you remove logs or enable only in debug mode?

**Comment by dusanbartos** [comment]
Hi, logs are coupled with `Timber` setup (take a look [here](https://github.com/JakeWharton/timber) if you are not familiar with it), so logging will be disabled if you don't attach a debug tree in your app (let's say for release version only)

Typically, I use code similar to this to make this setup
```
if (BuildConfig.DEBUG) {
    Timber.plant(new Timber.DebugTree());
} 
```

**Comment by miguelslemos** [comment]
Hi, I'm talking about RxLog see [here](https://github.com/Team-SOFTsk/ObservableAdapter/blob/master/observablecollection/src/main/java/sk/teamsoft/observablecollection/ObservableAdapter.java#L103)

**Comment by dusanbartos** [comment]
RxLog uses Timber internally, so here applies the same principle

**Comment by dusanbartos** [comment]
but I guess in this particular case, the log will be removed as soon as the library reaches version 1.0.0

**Comment by miguelslemos** [comment]
@doodeec when will be released v1?

**Comment by dusanbartos** [comment]
@miguelslemos since there are no known bugs right now, I guess in about a week... the library is ready for that milestone, but I wanted to run some more memory profiling before making it official... I will then have some more time to mirror the logic to rxjava1 and also to create a kotlin duplicate of the library

**Comment by dusanbartos** [comment]
logs were removed in 0.9.3
